database:
  type: 'sqlite'
  host: ''
  port: ''
  username: ''
  password: ''
  database: 'test_db.db'
  synchronize: false
  migrations: false
  cli:
    "migrationsDir": "test/e2e/migrations"
jwt:
  secret: 'secret_code'
  expiresIn: 3600
  ignoreExpiration: false
security:
  headerTokenToLogin: null
  whitelistedIp: null
runtime:
  habitat:
    buildingZones:
      counterForNewHabitat: 10
      isPossibleToCreateNewZones: true
    buildingQueue:
      maxElementsInQueue: 5
      allowMultipleLevelUpdate: true
    onStart:
      resources:
        - id: 'wood'
          amount: 30
        - id: 'coal'
          amount: 5
      buildings:
        - id: 'warehouse'
          localBuildingZoneId: 1
          level: 1
        - id: 'university'
          localBuildingZoneId: 2
          level: 1
  mechanics:
    resources:
      calculation: 'no-distance-simple-multiply'
      warehouse: 'base-resource-summary'
    queue:
      resourceConsumer: 'simple-resource-consumer'
